config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    get 'admins/sign_up' => 'admins/registrations#new', as: 'new_admin_registration'
    post 'admins' => 'admins/registrations#create', as: 'admin_registration'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
  end

  devise_for :users, skip: :all
  devise_scope :user do
    get 'users/sign_in' => 'users/sessions#new', as: 'new_user_session'
    post 'users/sign_in' => 'users/sessions#create', as: 'user_session'
    delete 'users/sign_out' => 'users/sessions#destroy', as: 'destroy_user_session'
    get 'users/sign_up' => 'users/registrations#new', as: 'new_user_registration'
    post 'users' => 'users/registrations#create', as: 'user_registration'
    get 'users/password/new' => 'users/passwords#new', as: 'new_user_password'
  end
  
  resources :blogs
  get 'homes/top'
  root 'homes#top'

  namespace 'admins' do
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :create, :edit, :update]
    resources :footprints, only: [:index, :create, :edit, :update, :destroy]
    resources :admins, only: [:edit, :update]
    resources :dashboards, only: [:index, :create]
  end

  namespace 'users' do
    resources :users, only: [:index, :show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :footprints, dependent: :destroy

end

app/controllers/admins/genres_controller.rb
class Admins::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genres = Genre.all
    @genre = Genre.new
    # @genre.target = 0
    # @genres.each do |genre|
    #   @genre_targets = genre.find(:target => true).footprints.sum
    # end
    # byebug
    # if @genre_targets.target == true
    #   @genre_target += @genre_targets.sum(:price)
      # byebug
    # end
    # @genres.each.select do |genre|
    #   genre.target == true
    #   @genre_targets = genre.footprints.sum(:price)
    # end
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admins_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admins_genres_path
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to admins_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(
      :name,
      :target
    )
  end

end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/views/admins/genres/edit.html.erb
<div class="container">
  <div class="genre_edit">
    <h3>ジャンル編集</h3>
    <%= form_with model: @genre, url: admins_genre_path(@genre), local: true do |f| %>
    <p>
      名称：
      <%= f.text_field :name %>
      <%= f.check_box :target, :as => :boolean %> 集計対象
      <%= f.submit "更新", class: "btn btn-success" %>
    </p>
    <% end %>
  </div>
</div>

app/views/admins/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <div class="page_title"><h3>ジャンル</h3></div><br>
      <%= form_with model: @genre, url: admins_genres_path(@genre), local: true do |f| %>
      <div class="genre_create">
          <p>ジャンル名：<%= f.text_field :name %>
          <%= f.check_box :target, :as => :boolean, checked:false %> 集計対象
          <%= f.submit '追加', class: "btn btn-primary"%></p>
      </div>    
      <% end %>
    </div>
    <div class="col-sm-6">
      <canvas id="genre-graph2"></canvas>
    </div>
  </div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>ジャンル名</th>
          <th>集計対象</th>
          <th>会計数</th>
          <th class="text-right">合計 ■ <%= Footprint.where(:genre_id => Genre.where(:target => true).ids).sum(:price).to_s(:delimited) %></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @genres.each do |genre| %>
        <%# @sum = 0 %>
          <tr>
            <td><%= link_to genre.name, admins_footprints_path(:genre_id => genre.id) %></td>
            <td class="text-center">
              <% if genre.target == true %>
                ■
              <% end %>
            </td>
            <td class="number"><%= genre.footprints.count %></td>
            <td class="number"><%= genre.footprints.sum(:price).to_s(:delimited) %></td>
            <td><%= link_to "変更", edit_admins_genre_path(genre), class: "btn btn-warning btn-sm" %></td>
            <td><%= link_to "削除", admins_genre_path(genre), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger btn-sm" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

</div>