config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    get 'admins/sign_up' => 'admins/registrations#new', as: 'new_admin_registration'
    post 'admins' => 'admins/registrations#create', as: 'admin_registration'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
  end

  devise_for :users, skip: :all
  devise_scope :user do
    get 'users/sign_in' => 'users/sessions#new', as: 'new_user_session'
    post 'users/sign_in' => 'users/sessions#create', as: 'user_session'
    delete 'users/sign_out' => 'users/sessions#destroy', as: 'destroy_user_session'
    get 'users/sign_up' => 'users/registrations#new', as: 'new_user_registration'
    post 'users' => 'users/registrations#create', as: 'user_registration'
    get 'users/password/new' => 'users/passwords#new', as: 'new_user_password'
  end
  
  resources :blogs
  get 'homes/top'
  root 'homes#top'

  namespace 'admins' do
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :create, :edit, :update]
    resources :footprints, only: [:index, :create, :edit, :update, :destroy]
    resources :admins, only: [:edit, :update]
    resources :dashboards, only: [:index, :create]
  end

  namespace 'users' do
    resources :users, only: [:index, :show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_rich_text :body
  attachment :image
  belongs_to :category
  acts_as_taggable

  validates :title, :category_id, :web_address, presence: true
 

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :blogs, dependent: :destroy
end

app/models/footprint.rb
class Footprint < ApplicationRecord
  belongs_to :genre

  enum result: {
    oubo: 0,
    ng: 1,
    ichji: 2,
    niji: 3,
    sanji: 4,
    naitei: 5
  }
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :footprints, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
        case resource
        when User
            root_path
        when Admin
            admins_dashboards_path
        end
    end

    def after_sign_out_path_for(resource)
        case resource
        when :user
            root_path
        when :admin
            new_admin_session_path
        end
    end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]
  before_action :set_categories, only: [ :show, :new, :edit, :update ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    # byebug
    @blog = Blog.find(params[:id])
    @blogs = Blog.order('updated_at desc').limit(15)
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(
        :title,
        :body,
        :summary,
        :image,
        :category_id,
        :web_address,
        :tag_list
      )
    end

    def set_categories
      @categories = Category.all
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    if params[:category_id] === nil && params[:search] === nil
      @blogs = Blog.all.order(updated_at: :desc)
    elsif params[:search] === nil
      @blogs = Blog.where(category_id: params[:category_id])
    else
      @blogs = Blog.where('title like ?', '%' + params[:search] + '%')
    end
    @categories = Category.all
    @footprints = Footprint.where(genre_id: 5)

  end
end

app/helpers/admins/admins_helper.rb
module Admins::AdminsHelper
end

app/helpers/admins/categories_helper.rb
module Admins::CategoriesHelper
end

app/helpers/admins/dashboards_helper.rb
module Admins::DashboardsHelper
end

app/helpers/admins/footprints_helper.rb
module Admins::FootprintsHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/work_times_helper.rb
module Admins::WorkTimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def default_meta_tags
    {
      site: 'いまいちなサイト',
      title: 'トップページ',
      reverse: true,
      charset: 'utf-8',
      description: 'ご訪問ありがとうございます。blogをruby on ralesで作成しました。',
      keywords: 'rails,ruby,プログラミング,bike,coffee',
      canonical: request.original_url,
      separator: '|',
      icon: [
        { href: image_url('coffee.png') }
      ],
      og: {
        site_name: :site, # もしくは site_name: :site
        title: :title, # もしくは title: :title
        description: :description, # もしくは description: :description
        type: 'blogsite',
        url: request.original_url,
        image: image_url('coffee.png'),
        locale: 'ja_JP',
      },
      twitter: {
        card: 'summary_large_image',
        site: '@fumihisa_y',
      }
    }
  end

  # def default_meta_tags
  #   {
  #     site: 'いまいちなサイト',
  #     title: 'トップページ',
  #     reverse: true,
  #     charset: 'utf-8',
  #     description: 'ご訪問ありがとうございます。blogをruby on ralesで作成しました。',
  #     keywords: 'rails,ruby,プログラミング,bike,coffee',
  #     separator: '|',
  # icon: [
  #   { href: image_url('coffee.png') }
  # ],
  #     og: defalut_og,
  #     twitter: default_twitter_card
  #   }
  # end
  
  # private
  
  # def defalut_og
  #   {
  #     title: :full_title,          # :full_title とすると、サイトに表示される <title> と全く同じものを表示できる
  #     description: :description,   # 上に同じ
  #     url: request.original_url,
  #     image: 'https://example.com/hoge.png'
  #   }
  # end
  
  # def default_twitter_card
  #   {
  #     card: 'summary_large_image', # または summary
  #     site: '@fumihisa_y'            # twitter ID
  #   }
  # end

  
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admins/admins/edit.html.erb
<div class="container">
  <div class="admins_edit">
    <%= form_with model: @admin, url: admins_admin_path(@admin), local: true do |f| %>
    <P>
      名前：
      <%= f.text_field :name %>
      <%= f.submit "更新" %>
    </P>
    <% end %>
  </div>
</div>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/admins/shared/_sub_content.html.erb
<div class="sub-wrapper">
  <div class="container-fluid sub-container">
    <div class="row sub">
      <div class="col-md-8 col-xs-12 profile">
        <h2 class="profile-title">About Me</h2>
        <div class="col-md-5 col-sm-5 col-xs-5 profile-image">
          <%= image_tag 'profile-image', class: "profile-image--item" %>
        </div>
        <div class="col-md-7 col-sm-7 col-xs-7 profile-info">
          <p class="profile-info--name">fumiblog</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_admin_side.html.erb
<div class="admin-side">
  <div class="admin-side--header">
    <%= fa_icon "home" %><%= link_to 'hirozak', root_path, target: "_blank" %>
  </div>
  <div class="admin-side--menu">
    <ul>
      <li class="admin-side--menu_item">
        <%= fa_icon "bar-chart" %><%= link_to "Dashboard", admin_root_path %>
      </li>
      <li class="admin-side--menu_item">
        <%= fa_icon "pencil-square-o" %><%= link_to "New Post", new_admin_post_path %>
      </li>
      <li class="admin-side--menu_item">
        <%= fa_icon "file-code-o" %><%= link_to "All Posts", all_admin_posts_path %>
      </li>
      <li class="admin-side--menu_item__sub">
        <%= link_to "- Published", published_admin_posts_path %>
      </li>
      <li class="admin-side--menu_item__sub">
        <%= link_to "- Drafts", drafts_admin_posts_path %>
      </li>
      <li class="admin-side--menu_item">
        <%= fa_icon "tags" %><%= link_to "Category", admin_categories_path %>
      </li>
      <!-- <li class="admin-side--menu_item">
        <%= fa_icon "hashtag" %><%= link_to "Tag", "#" %>
      </li> -->
      <li class="admin-side--menu_item">
        <%= fa_icon "sign-out" %><%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_advertising.html.erb
<a href="https://px.a8.net/svt/ejp?a8mat=3BT05G+912P2Q+3XAE+BXYE9" rel="nofollow">
<img border="0" width="300" height="250" alt="" src="https://www26.a8.net/svt/bgt?aid=201227524546&wid=001&eno=01&mid=s00000018311002006000&mc=1"></a>
<img border="0" width="1" height="1" src="https://www14.a8.net/0.gif?a8mat=3BT05G+912P2Q+3XAE+BXYE9" alt="">
<a href="https://px.a8.net/svt/ejp?a8mat=3B9R0Y+GEM0VM+50+2HUIWH" rel="nofollow">
<img border="0" width="300" height="300" alt="" src="https://www28.a8.net/svt/bgt?aid=200329234992&wid=001&eno=01&mid=s00000000018015091000&mc=1"></a>
<img border="0" width="1" height="1" src="https://www.net/013.a8.gif?a8mat=3B9R0Y+GEM0VM+50+2HUIWH" alt="">

app/views/shared/_blog_list.html.erb
<div class="container">
  <div class="row">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>最近更新の15タイトル</th>
        </tr>
      </thead>
      <% @blogs.each do |blog| %>
      <tbody>
        <tr>
          <td><%= link_to blog.title, blog_path(blog) %></td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer>
  <p>©Copyright 2019 hirozak.All Rights Reserved.</p>
</footer>

app/views/shared/_header_image.html copy.erb
<div class="top-header">
  <%= image_tag 'top-header', class: "top-header--image hidden-xs" %>
  <%= image_tag 'top-header-xs', class: "top-header--image visible-xs" %>
</div>

app/views/shared/_header_image.html.erb
<div id="carouselsample-1" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag 'code3.png', class: 'd-block w-100' %>
    </div>
    <div class="carousel-item">
      <%= image_tag 'coffee4.png', class: 'd-block w-100' %>
    </div>
    <div class="carousel-item">
      <%= image_tag 'code3.png', class: 'd-block w-100' %>
    </div>
  </div>
</div>

app/views/shared/_header_menu.html.erb
<div class="top-menu">
  <div class="container-fluid">
    <table class="top-menu--list">
      <tr>
        <th><%= link_to "All", posts_path, class: "top-menu--list-item" %></th>
        <th><%= link_to "Life", category_path("Life"), class: "top-menu--list-item" %></th>
        <th><%= link_to "Gadgets", category_path("Gadgets"), class: "top-menu--list-item" %></th>
        <th><%= link_to "Tech", category_path("tech"), class: "top-menu--list-item" %></th>
        <th><%= link_to "Music", category_path("Music"), class: "top-menu--list-item" %></th>
        <th><%= link_to "About".html_safe, "../about", class: "top-menu--list-item" %></th>
      </tr>
    </table>
  </div>
</div>

app/views/shared/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark" >
    <a href="" class="navbar-brand"><%= link_to "Fumiblog", homes_top_path, {class: "btn btn-primary"} %></a>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#menu">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div id="menu" class="collapse navbar-collapse">
      <% if user_signed_in? %>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><a href="" class="nav-link">　<%= Date.current.strftime('%Y年%m月%d日') %>（<%= Time.now.strftime("%A") %>）</a></li>
          <li class="nav-item"><a href="<%= blogs_path %>" class="nav-link">blog</a></li>
          <li class="nav-item"><a href="<%= users_user_path(current_user) %>" class="nav-link">user</a></li>  
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item"><a href="<%= destroy_user_session_path %>" data-method="delete" class="nav-link">logout</a></li>
          <%= image_tag 'imagefumiblog.jpg', class: "rounded-circle", size: "40x40" %>
        </ul>
      <% elsif admin_signed_in? %>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><a href="" class="nav-link">　<%= Date.current.strftime('%Y年%m月%d日') %>（<%= Time.now.strftime("%A") %>）</a></li>
          <li class="nav-item"><a href="<%= admins_dashboards_path %>" class="nav-link">dashboard</a></li>
          <li class="nav-item"><a href="<%= blogs_path %>" class="nav-link">blog</a></li>
          <li class="nav-item"><a href="<%= admins_genres_path %>" class="nav-link">genre</a></li>
          <li class="nav-item"><a href="<%= admins_categories_path %>" class="nav-link">category</a></li>
          <li class="nav-item"><a href="<%= admins_footprints_path %>" class="nav-link">footprint</a></li>
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item"><a href="<%= destroy_admin_session_path %>" data-method="delete" class="nav-link">logout</a></li>
          <%= form_tag(root_path, method: :get) do %>
            <%= text_field_tag "search" %>
            <%= submit_tag("Search") %>
          <% end %>
          <%= image_tag 'fumiblog2.jpg', class: "rounded-circle", size: "40x40" %>
        </ul>
      <% else %>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><a href="" class="nav-link">　<%= Date.current.strftime('%Y年%m月%d日') %>（<%= Time.now.strftime("%A") %>）</a></li>
          <li class="nav-item"><a href="<%= new_user_session_path %>" class="nav-link">会員の方</a></li>
          <li class="nav-item"><a href="<%= new_user_registration_path %>" class="nav-link">初めての方</a></li>
          <li class="nav-item"><a href="<%= new_user_registration_path %>" class="nav-link">初めての方</a></li>
        </ul>
        <ul class="navbar-nav">
          <%= form_tag(root_path, method: :get) do %>
            <%= text_field_tag "search" %>
            <%= submit_tag("Search") %>
          <% end %>
        </ul>
      <% end %>
    </div>
  </nav>
</header>

app/views/shared/_post.html.erb
<div class="col-md-6 post-list" ontouchstart="">
  <%= link_to post, class: "post-item" do %>
    <div class="post-item--side">
      <div class="post-item--image">
        <%= image_tag post.image.url(:thumb), class: "post-item--image__item" %>
      </div>
    </div>
    <div class="post-item--main">
      <p class="post-item--main_title"><%= post.title %></p>
      <p class="post-item--main_info">
        <span class="post-item--main_info__category">
          <%= post.category.name %>
        </span>
        <span class="post-item--main_info__date">
          <%= post.created_at.to_s(:published_on) %>
        </span>
      </p>
    </div>
  <% end %>
</div>

app/views/shared/_post_list.html copy.erb
<header>
  <%= render 'shared/navbar' %>
  <%= render 'shared/header_image' %>
  <%= render 'shared/header_menu' %>
  <div class="container-fluid slider-container">
    <div class="post-slider">
      <% @slider_posts.each do |slide_post| %>
        <div class="post-slider--item">
          <%= link_to slide_post do %>
            <%= image_tag slide_post.image.url(:thumb), class:"post-slider--item_image" %>
            <div class="post-slider--item_title">
              <%= slide_post.title %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</header>
<div class="main-wrapper">
  <div class="container-fluid main-container">
    <div class="posts-wrapper">
      <div class="posts">
        <h2 class="main-title"><%= main_title %></h2>
        <div class="posts-wrapper">
          <%= render partial: 'shared/post', collection: @posts %>
        </div>
        <div class="posts-pagination">
          <%= paginate @posts %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render 'shared/sub_content' %>
<%= render 'shared/footer' %>

app/views/shared/_post_list.html.erb
<header>
  <%= render 'shared/navbar' %>
  <%= render 'shared/header_image' %>
  <%= render 'shared/header_menu' %>
  <div class="container-fluid slider-container">
    <div class="post-slider">
      <% @slider_posts.each do |slide_post| %>
        <div class="post-slider--item">
          <%= link_to slide_post do %>
            <%= image_tag slide_post.image.url(:thumb), class:"post-slider--item_image" %>
            <div class="post-slider--item_title">
              <%= slide_post.title %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</header>
<div class="main-wrapper">
  <div class="container-fluid main-container">
    <div class="posts-wrapper">
      <div class="posts">
        <h2 class="main-title"><%= main_title %></h2>
        <div class="posts-wrapper">
          <%= render partial: 'shared/post', collection: @posts %>
        </div>
        <div class="posts-pagination">
          <%= paginate @posts %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render 'shared/sub_content' %>
<%= render 'shared/footer' %>

app/views/shared/_sub_content.html copy.erb
<div class="sub-wrapper">
  <div class="container-fluid sub-container">
    <div class="row sub">
      <div class="col-md-4 col-xs-12 this_blog">
        <h2 class="this_blog-title">This Blog</h2>
        <div class="this_blog-description">
          <p>このブログはRuby on Railsで開発しました。</p>
          <p>GitHubにて、ソースコードを公開しています。</p>
          <div class="this_blog-description--link">
            <div class="blogCard blogCard--noimg">
              <div class="blogCardCont">
                <div class="blogCardTxt">
                  <p class="blogCardTitle"><a href="https://github.com/fumiblog/BlogApp" target="_blank"><%= link_to "f", new_admin_session_path %>umiblog/BlogApp</a></p>
                  <p>fumiblog.BlogApp - my blog</p>
                </div>
              </div>
              <div class="blogCardFooter">
                <a href="https://github.com/fumiblog/BlogApp"><img src="https://github.githubassets.com/pinned-octocat.svg" alt="">github.com</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-8 col-xs-12 this_blog">
        <h2 class="this_blog-title">Who Are You</h2>
        <div class="this_blog-description">
          <p>このブログはRuby on Railsで開発しました。</p>
          <p>GitHubにて、ソースコードを公開しています。</p>
          <div class="this_blog-description--link">
            <div class="blogCard blogCard--noimg">
              <div class="blogCardCont">
                <div class="blogCardTxt">
                  <p class="blogCardTitle"><a href="https://github.com/fumiblog/BlogApp" target="_blank">fumiblog/BlogApp</a></p>
                  <p>fumiblog.BlogApp - my blog</p>
                </div>
              </div>
              <div class="blogCardFooter">
                <a href="https://github.com/fumiblog/BlogApp"><img src="https://github.githubassets.com/pinned-octocat.svg" alt="">github.com</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sub_content.html.erb
<div class="sub-wrapper">
  <div class="container-fluid sub-container">
    <div class="row sub">
      <div class="col-md-8 col-xs-12 profile">
        <h2 class="profile-title">About Me</h2>
        <div class="col-md-4 col-sm-4 col-xs-4 profile-image">
          <%= image_tag 'imagefumiblog', width: '50%', height: '50%', class: "profile-image--item" %>
        </div>
        <div class="col-md-7 col-sm-7 col-xs-7 profile-info">
          <p class="profile-info--name">fumiblog</p>
          <div class="profile-info--link">
            <%= link_to "https://twitter.com/xringoxr", {class: "profile-info--sns icon-sns icon-twitter", target: "_blank"} do %>
              <%= fa_icon "twitter 2x" %>
            <% end %>
            <%= link_to "https://www.instagram.com/hirozak/", {class: "profile-info--sns icon-sns icon-instagram", target: "_blank"} do %>
              <%= fa_icon "instagram 2x" %>
            <% end %>
            <%= link_to "https://github.com/hirozak", {class: "profile-info--sns icon-sns icon-github", target: "_blank"} do %>
              <%= fa_icon "github 2x" %>
            <% end %>
          </div>
          <div class="profile-info--description">
            <p>エンジニアを目指す</p>
            <p>プログラミング、バイク、ラーメン、珈琲が好きです。</p>
            <%= link_to "詳しく見る", "../about", class: "btn btn-outline-default btn-round" %>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-xs-12 this_blog">
        <h2 class="this_blog-title">This Blog</h2>
        <div class="this_blog-description">
          <p>このブログはfumiblogがRuby on Railsで開発しました。</p>
          <p>GitHubにて、ソースコードを公開しています。</p>
          <div class="this_blog-description--link">
            <div class="blogCard blogCard--noimg">
              <div class="blogCardCont">
                <div class="blogCardTxt">
                  <p class="blogCardTitle"><a href="https://github.com/hirozak/hirozak.space" target="_blank">fumiblog/BlogApp</a></p>
                  <p>fumiblog.link - my blog</p>
                </div>
              </div>
              <div class="blogCardFooter">
                <a href="https://github.com/hirozak/hirozak.space"><img src="https://github.githubassets.com/pinned-octocat.svg" alt="">github.com</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_usershow.html.erb
<div class="footprint">
  <p class="h4 p-2 dashboard_message">Welcome Back, <%= current_user.name %> !</p>
  <p>LV.</p>
</div>