config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    get 'admins/sign_up' => 'admins/registrations#new', as: 'new_admin_registration'
    post 'admins' => 'admins/registrations#create', as: 'admin_registration'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'
  end

  devise_for :users, skip: :all
  devise_scope :user do
    get 'users/sign_in' => 'users/sessions#new', as: 'new_user_session'
    post 'users/sign_in' => 'users/sessions#create', as: 'user_session'
    delete 'users/sign_out' => 'users/sessions#destroy', as: 'destroy_user_session'
    get 'users/sign_up' => 'users/registrations#new', as: 'new_user_registration'
    post 'users' => 'users/registrations#create', as: 'user_registration'
    get 'users/password/new' => 'users/passwords#new', as: 'new_user_password'
  end
  
  resources :blogs
  get 'homes/top'
  root 'homes#top'

  namespace 'admins' do
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :create, :edit, :update]
    resources :footprints, only: [:index, :create, :edit, :update, :destroy]
    resources :admins, only: [:edit, :update]
    resources :dashboards, only: [:index, :create]
  end

  namespace 'users' do
    resources :users, only: [:index, :show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admins/dashboards_controller.rb
class Admins::DashboardsController < ApplicationController
  def index
    @footprints = Footprint.where(genre_id: 5)
    @data = Footprint.where(genre_id: 1)
    @datas = @data.select(:date, :price)
    @times = [date:2021-01-28]
    gon.genre_json = Genre.pluck(:name)
    gon.footprint_json = Footprint.group(:genre_id).sum(:price).values
    gon.blog_writingdate = Blog.group("date(created_at)").pluck("date(created_at)")
    gon.blog_writingcount = Blog.group("date(created_at)").count.values
    gon.blog_writingmonth = Blog.all.group_by{ |record| record.created_at.strftime("%Y-%m") }.keys
    @month_record = Blog.all.group_by{ |record| record.created_at.strftime("%Y-%m") }.values
    gon.blog_writingmonthcount = @month_record.count
    # byebug
  end

  def create
   
  end

  def update
   
  end
  
  private

end

app/helpers/admins/dashboards_helper.rb
module Admins::DashboardsHelper
end

app/views/admins/dashboards/index.html.erb
<div class="container-fruid alert alert-secondary">
  <h3 class="m-3">Dashboard</h3>
    <!--
  <div class="row">
    <div class="col-md-3">
      <div class="orverflow-auto dashboard_menu m-3 p-2 bg-dark" style= "width:100%; height:1000px;">
        <p class="h4 text-white p-3"><i class="fas fa-home"></i><%= link_to " home", admins_dashboards_path, :style=>"color:white;" %></p>
        <p class="h4 text-white p-3"><i class="fas fa-blog"></i><%= link_to " blogs", blogs_path, :style=>"color:white;" %></p>
        <p class="h4 text-white p-3"><i class="fas fa-hospital"></i><%= link_to " genres", admins_genres_path, :style=>"color:white;" %></p>
        <p class="h4 text-white p-3"><i class="fas fa-hospital"></i><%= link_to " categories", admins_categories_path, :style=>"color:white;" %></p>
      </div>
    </div>
      <div class="col-md-9">
    -->

    <div class="row dash mx-auto">
      <div class="col alert alert-primary text-primary m-3 p-3 overflow-auto small" style= "position: relative; max-height:17vh; width:60vw">
        <%= render 'shared/footprint'%>
        <img src="" alt="">
        </div>
        <div class="col bg-light text-secondary m-3 p-3" style= "position: relative; max-height:17vh; width:60vw">
      
        <div class="h1" id="timer">00:00.000</div>
        <button id="start">Start</button>
        <button id="stop">Stop</button>
        <button id="reset">Reset</button>
      </div>
    </div>
    <div class="row dash mx-auto">
      <div class="col bg-light text-secondary m-3 p-3" style="position: relative; max-height:17vh; width:60vw">
        <canvas id="genre_graph" height="100"></canvas>
      </div>
      <div class="col bg-light text-secondary m-3 p-3" style="position: relative; max-height:17vh; width:60vw">
        <canvas id="blog_count" height="100"></canvas>
      </div>
    </div>
    <div class="row dash mx-auto">
      <div class="col bg-light text-secondary m-3 p-3" style="position: relative; max-height:17vh; width:60vw">
        <canvas id="" height="100"></canvas>
      </div>
      <div class="col bg-light text-secondary m-3 p-3" style="position: relative; max-height:17vh; width:60vw">
        <%= image_tag 'fumiblog.jpg', class: "rounded-circle", size: "100x100" %>
        <%= image_tag 'fumiblog2.jpg', class: "rounded-circle", size: "100x100" %>
        <p>48歳　　　　　51歳</p>
      </div>
    </div>
    <!--
    -->

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
    <script>
      'use strict';

      var ctx = document.getElementById("genre_graph");
        new Chart(ctx, {
          type: 'horizontalBar',
          data: {
            labels: gon.genre_json,
            // labels: ["HomePayment", "recruit", "HomeApPliance", " insurance"],
            datasets: [{
              label: '分類毎支出',
              backgroundColor: '#20B2AA',
              // data: $('.footprint_json').val()
              // data: [1363338, 0, 1050390, 1000000]
              data: gon.footprint_json
            }]
          }
        });

        var options = {
          scales: {
              xAxes: [{
                  ticks: {
                      min: 500000
                  }
              }]
          }
      };
      
      var ctx = document.getElementById("blog_count");
        new Chart(ctx, {
          type: 'line',
          data: {
            labels: gon.blog_writingdate,
            datasets: [{
              label: 'ブログ作成件数',
              backgroundColor: '#20B2AA',
              data: gon.blog_writingcount
            }]
          }
        });

        // var opsitons = {
        //   scales: {
        //     xAxes: [{
        //       ticks: {
        //         min: 
        //       }
        //     }]
        //   }
        // };

      {
        const timer = document.getElementById('timer');
        const start = document.getElementById('start');
        const stop = document.getElementById('stop');
        const reset = document.getElementById('reset');

        let startTime;
        let timeoutId;
        let elapsedTime = 0;

        function countUp() {
          const d = new Date(Date.now() - startTime + elapsedTime);
          const m = String(d.getMinutes()).padStart(2, '0');
          const s = String(d.getSeconds()).padStart(2, '0');
          const ms = String(d.getMilliseconds()).padStart(3, '0');
          timer.textContent = `${m}:${s}.${ms}`;

          timeoutId = setTimeout(() => {
            countUp();
          }, 10);
        }
        
        function setButtonStateInitial(){
          start.disabled = false;
          stop.disabled = true;
          reset.disabled = true;
        }
        function setButtonStateRunning(){
          start.disabled = true;
          stop.disabled = false;
          reset.disabled = true;
        }
        function setButtonStateStopped(){
          start.disabled = false;
          stop.disabled = true;
          reset.disabled = false;
        }

        setButtonStateInitial();

        start.addEventListener('click', () => {
          setButtonStateRunning();
          startTime = Date.now();
          countUp();
        });

        stop.addEventListener('click', () => {
          setButtonStateStopped();
          clearTimeout(timeoutId);
          elapsedTime += Date.now() - startTime;
        });

        reset.addEventListener('click', () => {
          setButtonStateInitial();
          timer.textContent = '00:00.000';
          elapsedTime = 0;
        });
      }
    </script>
</div>